#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries. Simply type the menu entries you want to add after this comment. Be careful not to change the ‘exec tail’ line above.
set check_signatures=enforce
export check_signatures

# define superusers
set superusers=”root”
export superusers

# define users
password_pbkdf2 root grup.pbkdf2.sha512.10000
